@echo off
echo ==========================================
echo      UPDATING REPORT FOOTER
echo ==========================================
echo Mengganti tulisan 'Generated by Antigravity' menjadi branding resmi perusahaan.

echo 1. Packing files...
cd api
tar -cf ../update_report_footer.tar resources/views/emails/reports/weekly.blade.php
cd ..

echo.
echo 2. Uploading...
set VPS_USER=root
set VPS_IP=202.10.44.146
set REMOTE_PATH=/var/www/isotank-system

scp update_report_footer.tar %VPS_USER%@%VPS_IP%:%REMOTE_PATH%/

echo.
echo 3. Installing...
ssh %VPS_USER%@%VPS_IP% "cd %REMOTE_PATH% && tar -xf update_report_footer.tar && rm update_report_footer.tar"

echo.
echo ==========================================
echo        SUCCESS
echo ==========================================
echo Laporan Weekly Report sudah diperbaiki.
echo Silakan cek Preview lagi.
pause
