@echo off
echo ==========================================
echo      UPDATING REPORT FOOTER (V2 ROBUST)
echo ==========================================
echo Mengganti tulisan 'Generated by Antigravity' (Mode Stabil).

echo 1. Packing files...
cd api
tar -cf ../update_report_footer_v2.tar resources/views/emails/reports/weekly.blade.php
cd ..

echo.
echo 2. Uploading...
set VPS_USER=root
set VPS_IP=202.10.44.146
set REMOTE_PATH=/var/www/isotank-system

scp update_report_footer_v2.tar %VPS_USER%@%VPS_IP%:%REMOTE_PATH%/

echo.
echo 3. Installing...
echo (Anda diminta password untuk terakhir kalinya)
ssh -t %VPS_USER%@%VPS_IP% "cd %REMOTE_PATH% && tar -xvf update_report_footer_v2.tar && rm -f update_report_footer_v2.tar && echo DONE_SUCCESS"

echo.
echo ==========================================
echo        SUCCESS
echo ==========================================
echo Laporan Weekly Report sudah diperbaiki.
pause
